version: '3.1'

services:
  wordpress:
    network_mode: host
    build:
      context: ./
      dockerfile: compose/local/wordpress/Dockerfile

    ports:
     - "80:80"
    environment:
      WORDPRESS_DB_HOST: 127.0.0.1
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1

    volumes:
      - wp-plugins:/var/www/html/wp-content/plugins
      - ./src:/var/www/html/wp-content/plugins/wp-mapasculturais
      - wp-uploads:/var/www/html/wp-content/uploads
      - ./themes:/var/www/html/wp-content/themes

  db:
    network_mode: host
    image: mysql:5.7

    ports:
     - "3306:3306"

    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-data:/var/lib/mysql


  mapas-nginx:
    image: hacklab/mapasculturais-nginx:latest
    volumes:
      - mapas-assets:/var/www/html/assets
      - mapas-public-files:/var/www/html/files

    ports:
     - "8080:80"
    depends_on:
      - mapasculturais

  mapasculturais:
    image: hacklab/mapasculturais:develop
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=db-mapas
      - DB_NAME=mapas
      - DB_USER=mapas
      - DB_PASS=mapas
      - APP_LCODE=pt_BR
      - APP_MODE=production
      - PENDING_PCACHE_RECREATION_INTERVAL=30
      - JOBS_INTERVAL=30
    volumes:
      - mapas-assets:/var/www/html/assets
      - mapas-public-files:/var/www/html/files
      - mapas-private-files:/var/www/private-files

    depends_on:
      - db-mapas

  db-mapas:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - mapas-db-data:/var/lib/postgresql/data
      - ./compose/local/mapas.sql:/docker-entrypoint-initdb.d/mapas.sql


volumes:
  db-data:
  mapas-db-data:
  mapas-public-files:
  mapas-private-files:
  mapas-assets:
  wp-uploads:
  wp-plugins: